version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_LOG4J_LOGLEVEL: WARN
  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_REST_DEBUG: WARN
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - ./migration/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - volume_files:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: Strong#password2023
    command: server --console-address ":9001" /data

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking
    ports:
      - "3306:3306"
    volumes:
      - ./migration/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - volume_files:/upload
    working_dir: /app
    environment:
      - MONGO_URI=mongodb://root:password@mongo:27017
      - MYSQL_URI=root:root@tcp(mysql:3306)/banking?parseTime=true&autocommit=true
      - KAFKA_URI=broker:9092
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=Strong#password2023
      - CSV_VOLUME=/upload

    depends_on:
      - mongo
      - broker
      - mysql
      - zookeeper
      - minio

volumes:
  mongodb_data:
  volume_files:
